### PR TITLE
Change all stats to unsigned integer to allow reporting full 64kB of …

### PR DESCRIPTION
**Pull request by SeppoTakalo**
…heap.

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
Actually, If we do anything for this.. should we probably change all types to `size_t` or `ssize_t`?

Feels a bit stupid to limit ourself to 64kB internally on devices with 256kB of RAM.

**Comment by kjbracey-arm** [comment]
This is a legacy "be nice to 8-bit or 16-bit platforms" thing. I think size_t would probably be appropriate.

Conceivably ssize_t might be safer for ones that are already signed - it's possible some sanity-check code checks things going negative on some sort of imbalance.

**Comment by artokin** [comment]
+1, would be nice to get correction merged.
Heap statistics are traced in nanostack_border_router and we get figures like:
```DutThread: [INFO][app ]: Heap size: 50000, Reserved: 49360, Reserved max: 32424, Alloc fail: 254```

**Comment by artokin** [comment]
This change is made in https://github.com/PelionIoT/nanostack-libservice/pull/60, this PR can be closed.

**Pull request closed without merging**
